#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1462935634                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : fr                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://pierreboudoin.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : La meilleure application de santé autour des médicaments.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Pierre Boudoin                                
your_link                                 : https://pierreboudoin.com                     
your_city                                 : Bordeaux                                
email_address                             : pierre.boudoin@gmail.com
facebook_username                         :                                           
instagram_username                        : pboudoin
twitter_username                          : pboudoin
github_username                           : pboudoin
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Rappels de Médicament et de Pilule
    description                           : Programmez vos rappels pour la prise de vos traitements. De nombreuses options sont possibles : quotidiennement, certains jours de la semaine, périodiquement, etc. 
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Synchronisation iCloud 
    description                           : Toutes vos données sont synchronisées sur votre espace iCloud Drive et sont donc disponibles sur tout vos périphériques iOS.
    fontawesome_icon_name                 : cloud

  - title                                 : Notices
    description                           : Consultez rapidement les notices des médicaments dans un format optimisé pour une consultation sur téléphone (iPhone) ou tablette (iPad)
    fontawesome_icon_name                 : play-circle

  - title                                 : Fiche d'informations
    description                           : Consultez toutes les informations sur vos médicaments : composition, alternatives, SMR, ASMR, Notice, RCP, prix, taux de remboursement, etc.
    fontawesome_icon_name                 : sync

  - title                                 : Scanner de médicaments
    description                           : Utilisez la camera de votre iPhone pour scanner le code-barre ou le datamatrix de vos boites de médicaments et accédez instantanément à toutes les informations.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Gestion du Stock
    description                           : Enregistrez tous les médicaments que vous avez en stock dans vos armoires à pharmacie ainsi vous pourrez recevoir uen alerte lorsque votre stock devient faible ou lorsque certains médicaments atteignent leur date d'expiration.
    fontawesome_icon_name                 : star

  - title                                 : Ordonnances
    description                           : Scannez vos ordonnances et enregistrez dans l'application
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : CIM-11
    description                           : Consultez la nomenclature CIM-11
    fontawesome_icon_name                 : link

  - title                                 : Vue Synthèse
    description                           : Grâce à la vue synthèse, en un coup d'oeil vous saurez ou vous en êtes de vos traitements et de l'état de votre stock de médicaments.
    fontawesome_icon_name                 : info-circle

  - title                                 : Widgets
    description                           : A l'aide des widgets, vous n'avez même plus besoin de lance l'application pour connaitre l'avancée de vos traitements pour la journée.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#291BBD"
topbar_transparency                       : 1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#291BBD"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FFFFFF"
feature_icons_background_color            : "#291BBD"

social_icons_foreground_color             : "#FFFFFF"
social_icons_background_color             : "#291BBD"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
